title: DongInn Kim
url: "http://homes.soic.indiana.edu"
baseurl: "/dikim"

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

favicon:
    favicon_location: http://www.iu.edu/favicon.ico

# Make sure to exclude 'vendor' from the build 
exclude: [vendor, "Gemfile", "Gemfile.lock"]
